# Notebook 3A - Wed/Thurs
## Calculations with vector math using components and numpy arrays
## Total Points: 6
#### PHYS 225 Intro to Computational Physics, Fall 2020

In [1]:
import numpy as np

## Gravity

The vector equation for the gravitational force acting on a mass $m_2$ at position $\vec{r}_2$ due to another mass $m_1$ at a position $\vec{r}_1$ is given by

$$ \vec{F}_\textrm{1 on 2} = -G\frac{m_1 m_2}{r^2}\hat{r} $$
where the "relative position" vector pointing between the two masses is given by

$$\vec{r} = \vec{r}_2 - \vec{r}_1$$ 

and the unit vector pointing in the direction toward $m_2$ from $m_1$ is $\hat{r}$




# Task 1: Neatly, on a piece of paper answer the following questions (1 pt)
1. Draw a diagram showing $\vec{r}_1$ and $\vec{r}_2$ as well as the relative position vector $\vec{r}$ and unit vector $\hat{r}$, and the gravitational force $\vec{F}_\textrm{1 on 2}$.
1. Express $r=|\vec{r}|$ in terms of the position vectors $\vec{r}_1$ and $\vec{r}_2$.
1. Express the unit vector $\hat{r}$ in terms of the vectors $\vec{r}_1$ and $\vec{r}_2$.
1. Express $\vec{F}_\textrm{1 on 2}$ in terms of the vectors $\vec{r}_1$ and $\vec{r}_2$.
1. Express $r$ in terms of the position components $(x_1, y_1, z_1)$ and $(x_2, y_2, z_2)$.
1. Express $\hat{r}$ in terms of the position components $(x_1, y_1, z_1)$ and $(x_2, y_2, z_2)$.
1. Express $\vec{F}_\textrm{1 on 2}$ in terms of the position components $(x_1, y_1, z_1)$ and $(x_2, y_2, z_2)$.

**In the markdown cell below, include a photo of your work.** Note: there are two ways to include images
* The quick way
    * `![Text describing image](imagename.png)`
* An alternative that allows you adjust the image width (in this example set to 400 pixels)
    * `<img src="imagename.png" alt="Text describing image" width="400"/>`

**Ask Dr. Zwickl check over your answers!**

## Using Numpy Arrays as Vectors
In your physics classes you do a ***bunch*** of mathematical calculations with vectors. It will be really, really useful to be able to do some vector math in Python. Today we will learn how to:
* add two vectors
* take the difference between two vectors
* dot/scalar product of two vectors
* cross/vector product of two vectors
* find the length of a vector (also called a norm of a vector)

There are several ways to represent vectors in mathematical notation, such as 
* Unit vector notation: $\vec{u} = u_x \hat{i} + u_y \hat{j} + u_z \hat{k}$
* Or as a $1\times n$ matrix: $(u_x, u_y, u_z)$

The latter notation looks very much like a list or a numpy array. We can use numpy arrays as vectors in most cases.



# Task 2: Do the following vector calculations by hand (1 point)

For Task 2, and for the examples below assume: 
$$\vec{u} = 2 \hat{i} + 5 \hat{j} - 7 \hat{k}$$
$$\vec{v} = 3 \hat{i} + 3 \hat{j} + 3 \hat{k}$$

In the Markdown cell below, *type in your answers* to the following. Don't worry about the LaTeX, just make it readable.
1. $\vec{u} + \vec{v}$
1. $\vec{u} - \vec{v}$
1. $\vec{u} \cdot \vec{v}$
1. $\vec{u} \times \vec{v}$
1. $u = |\vec{u}|$
1. $v = |\vec{v}|$


### Example calculations for vector math
Execute the cells below to see example of adding, subtracting, and other operations on two numpy vectors.

In [2]:
# define the same two vectors as used in Task 2.
u = np.array([2, 5, -7])  # create a numpy array using vector components
v = np.array([3, 3, 3])   # create a numpy array using vector components
print(u)
print(v)

[ 2  5 -7]
[3 3 3]


In [3]:
# addition of two vectors
w1 = u + v
print(w1)

[ 5  8 -4]


In [4]:
# subtraction of two vectors
w2 = u - v
print(w2)

[ -1   2 -10]


In [5]:
# dot product of two vectors
w3 = np.dot(u,v)  # note the result is a scalar, not a vector
print(w3) 

0


In [6]:
# cross product of two vectors
w4 = np.cross(u,v) # the result is a vector (actually a numpy array of length 3)
print(w4)

[ 36 -27  -9]


In [7]:
# length of a vector using built-in norm function
u_length = np.linalg.norm(u)
print( u_length )

v_length = np.linalg.norm(v)
print( v_length )

# length of a vector using the pythagorean theorem
u_length = (u[0]**2 + u[1]**2 + u[2]**2)**0.5
print( u_length )  # gives the same result!

8.831760866327848
5.196152422706632
8.831760866327848


# Task 3: Computationally verify the cross-product is orthogonal to original two vectors (1 point)
1. The cross product $\vec{w}_4=\vec{u} \times \vec{v}$ should be orthogonal/perpindicular to both $\vec{u}$ and $\vec{v}$. Use the numpy vector math operations to show this for the example vectors `u` and `v` above.
1. Use numpy operations to carry out one or more calculations that demonstrate orthogonality in this special case.
1. Comment your code!

**Your answer should go in the code cell below**

In [8]:
# Insert code to computationally verify the cross-product is orthogonal to original two vectors.

#  Task 4: Define a function that returns the angle (in degrees) between two vectors (1 point)

**Function name:** `angle_span`

**Input parameters:** 
* u - a numpy array with three elements 
* v - a numpy array with three elements

**Returns output:** 
* theta - the angle **in degrees** between vectors u and v 

1. First write your function out using pencil and paper math.
1. Hint: How does the dot product of two vectors relate to the angle between them?

In [9]:
"""
Define a function angle_span(u, v) that takes in two arrays of length 3 and returns the angle between them in degrees.
"""
### BEGIN SOLUTION

def angle_span(u,v) :
    """ u and v are two numpy arrays of same length, treated as vectors
    """
    costheta = np.dot(u,v)/( np.linalg.norm(u) * np.linalg.norm(v) )
    theta = np.arccos(costheta)
    theta = np.degrees(theta)
    return theta

print( angle_span(u,v)-90)
u1 = np.array([1,0,0])
u2 = np.array([-1,-1,-1])
print( angle_span(u1, u2))
u1 = np.array([2.4, -6.7, 3.67])
print( angle_span(u1, -u1))
print( angle_span(u1, 2*u1))
    
### END SOLUTION

0.0
125.26438968275465
179.99999879258172
1.2074182697257333e-06


In [10]:
""" test cases for the angle_span() function"""

u = np.array([2, 5, -7]); v = np.array([3, 3, 3])
assert abs(angle_span(u, v) - 90)/90 < 1e-5 

u = np.array([1,0,0]); v = np.array([-1,-1,-1])
assert abs(angle_span(u, v) - 125.26438968)/125.26438968 < 1e-5

u = np.array([2.4, -6.7, 3.67])
assert abs(angle_span(u, -u) - 180)/180 < 1e-5 # anti-parallel vectors are 180 deg apart
assert abs(angle_span(u, 5*u) - 0) < 1e-5  # parallel vectors are 0 deg apart

# reset the definitions of u and v to match the example above
u = np.array([2, 5, -7]); v = np.array([3, 3, 3])

# Task 5: Define a function `F_grav_comp( )` that computes the gravitational force *with vector components* (1 pt)
**Function name:** `F_grav_comp()`

**Inputs (8 in total):** 
* `x1`, `y1`, `z1`, which represent the position $x_1$, $y_1$, $z_1$ of mass 1 in meters
* `x2`, `y2`, `z2`, which represent the position $x_2$, $y_2$, $z_2$ of mass 2 in meters
* `m1` and `m2` represent mass values $m_1$, $m_2$ in kg

**Output:** 
* a list with three components `[Fx, Fy, Fz]` representing the force components $F_x$, $F_y$, $F_z$

In [22]:
"""
Define the function F_grav_comp() which can be used to compute the graviational force
x1, y1, z1, position components in meters
x2, y2, z2, position components in meters
m1, m2, masses in kg
"""
from scipy.constants import G # import gravitational constant 

### BEGIN SOLUTION
def F_grav_comp(x1, y1, z1, x2, y2, z2, m1, m2) :
    r = ( (x2-x1)**2 + (y2-y1)**2 + (z2-z1)**2 )**0.5
    F_mag = G*m1*m2/r**2
    Fx = -F_mag * (x2-x1)/r
    Fy = -F_mag * (y2-y1)/r
    Fz = -F_mag * (z2-z1)/r
    return [Fx,Fy,Fz]

print(F_grav_comp(0,0,0,1,0,0, m1=70, m2=100))
print(F_grav_comp(0,0,0,1,0,0, m1=100, m2=70)) 
print(F_grav_comp(1,5,-4,2,5,-4, m1=100, m2=70)) 
print(F_grav_comp(0,0,0, 10/(3)**0.5, 10/(3)**0.5, 10/(3)**0.5, m1=100, m2=70)) 
print(F_grav_comp(-3,7,4,27,4,9, m1=100, m2=70)) 

result = np.array( F_grav_comp(0,0,0, 10/(3)**0.5, 10/(3)**0.5, 10/(3)**0.5, m1=100, m2=70) )
abs(result - np.array([-2.697297319215167e-09, -2.697297319215167e-09, -2.697297319215167e-09]))
### END SOLUTION

[-4.672009999999999e-07, -0.0, -0.0]
[-4.67201e-07, -0.0, -0.0]
[-4.67201e-07, -0.0, -0.0]
[-2.6973862311566217e-09, -2.6973862311566217e-09, -2.6973862311566217e-09]
[-4.910262433890484e-10, 4.910262433890484e-11, -8.183770723150807e-11]


array([8.89119415e-14, 8.89119415e-14, 8.89119415e-14])

Compute the gravitational force between two people separated by 1 meter. The force should be less than a micronewton.

The test result should look like 

    [-4.67201e-07, -0.0, -0.0]

In [23]:
# force between two people separated by 1 m
x1 = 0; y1 = 0; z1 = 0  # coordinates of person 1
x2 = 1; y2 = 0; z2 = 0  # corrdinates of person 2
m1 = 70 # mass in kg
m2 = 100 # mass in kg

F_grav_comp(x1,y1,z1,x2,y2,z2, m1, m2)  

[-4.672009999999999e-07, -0.0, -0.0]

In [30]:
""" Test cases for F_grav_comp, which takes 8 component inputs """

def vector_error(studentresult, instructorresult) :
    studentvec = np.array(studentresult)
    instructorvec = np.array(instructorresult)
    error = np.linalg.norm(studentvec - instructorvec)/np.linalg.norm(instructorvec)
    return error
    

# force between two people shoudl be less than a micronewton.
studentresult = F_grav_comp(0,0,0,1,0,0, m1=70, m2=100)
#print(result)

assert type(studentresult) == list  # check the type of the returned result is as-specified

# check if the force vector is very close to the test case calculation
instructorresult = [-4.67201e-07, -0.0, -0.0]
print(studentresult)
assert vector_error(studentresult, instructorresult ) < 1e-4

# revese m1 and m2 values
studentresult = F_grav_comp(0,0,0,1,0,0, m1=100, m2=70)
instructorresult = [-4.67201e-07, -0.0, -0.0]
print(studentresult)
assert vector_error(studentresult, instructorresult ) < 1e-4


# shift positions of both masses by equal amounts
studentresult = F_grav_comp(-3,-3,-3,-2,-3,-3, m1=100, m2=70)
instructorresult = [-4.67201e-07, -0.0, -0.0]
print(studentresult)
assert vector_error(studentresult, instructorresult ) < 1e-4

# move masses 10x farther apart
studentresult = F_grav_comp(-30,-30,-30,-20,-30,-30, m1=100, m2=70)
instructorresult = [-4.67201e-09, -0.0, -0.0]
print(studentresult)
assert vector_error(studentresult, instructorresult ) < 1e-4

# move masses 10x apart, include x, y, z displacement
studentresult = F_grav_comp(0,0,0, 10/(3)**0.5, 10/(3)**0.5, 10/(3)**0.5, m1=100, m2=70)
instructorresult = [-2.6973862311566217e-09, -2.6973862311566217e-09, -2.6973862311566217e-09]
print(studentresult)
assert vector_error(studentresult, instructorresult ) < 1e-4

del studentresult, instructorresult, vector_error

[-4.672009999999999e-07, -0.0, -0.0]
[-4.67201e-07, -0.0, -0.0]
[-4.67201e-07, -0.0, -0.0]
[-4.6720099999999995e-09, -0.0, -0.0]
[-2.6973862311566217e-09, -2.6973862311566217e-09, -2.6973862311566217e-09]


# Task 6: Define a function `F_grav_vec()` that computes the gravitational force *with numpy arrays* as position vectors (1 pt)
**Function name:** `F_grav_vec()`

**Inputs (4 in total):** 
* `pos1`, will be a length 3 numpy array representing the position vector of $m_1$
* `pos2`, will be a length 3 numpy array representing the position vector of $m_2$
* `m1` and `m2` represent mass values $m_1$, $m_2$

**Output:** 
`F_grav`, a length 3 `numpy array` representing the force vector $\vec{F}_\textrm{grav}$

In [32]:
"""
Define the function F_grav_vec() which can be used to compute the graviational force
pos1, numpy array of positions (x1,y1,z1) in meters
pos2, numpy array of positions (x2,y2,z2) in meters
m1, m2, masses in kg
"""
from scipy.constants import G # import gravitational constant 

### BEGIN SOLUTION
def F_grav_vec(pos1, pos2, m1, m2) :
    r = np.linalg.norm(pos2-pos1)
    F_mag = G*m1*m2/r**2
    r_unit = (pos2-pos1)/r
    F_grav = -F_mag*r_unit
    return F_grav

pos1 = np.array([0,0,0]); pos2 = np.array([1,0,0])
print(F_grav_vec(pos1,pos2, m1=70, m2=100))
print(F_grav_vec(pos1,pos2, m1=100, m2=70)) 
print(F_grav_vec(pos1+4,pos2+4, m1=100, m2=70))
print(F_grav_vec(10*(pos1+4),10*(pos2+4), m1=100, m2=70))  
F_grav_vec(10*(pos1+4),10*(pos2+4), m1=100, m2=70)
### END SOLUTION

[-4.67201e-07 -0.00000e+00 -0.00000e+00]
[-4.67201e-07 -0.00000e+00 -0.00000e+00]
[-4.67201e-07 -0.00000e+00 -0.00000e+00]
[-4.67201e-09 -0.00000e+00 -0.00000e+00]


array([-4.67201e-09, -0.00000e+00, -0.00000e+00])

The test below should produce an output that looks like

    array([-4.67201e-07, -0.000000e+00, -0.000000e+00])


In [33]:
# force between two people separated by 1 m
pos1 = np.array([0,0,0]) # coordinates of person 1
pos2 = np.array([1,0,0])  # corrdinates of person 2
m1 = 70 # mass in kg
m2 = 100 # mass in kg

F_grav_vec(pos1,pos2, m1, m2)  

array([-4.67201e-07, -0.00000e+00, -0.00000e+00])

In [37]:
## """Check the F_grav_vec against test cases (same situations as for F_grav1)"""

def vector_error(studentvec, instructorvec) :
    error = np.linalg.norm(studentvec - instructorvec)/np.linalg.norm(instructorvec)
    return error
    

# force between two people shoudl be less than a micronewton.
pos1 = np.array([0,0,0]); pos2 = np.array([1,0,0])
studentresult = F_grav_vec(pos1,pos2, m1=70, m2=100)
assert type(studentresult) == np.ndarray  # check datatype of students' result

instructorresult = np.array( [-4.67201e-07, -0.0, -0.0] )
print(studentresult)
assert vector_error(studentresult, instructorresult ) < 1e-4

# revese m1 and m2 values
studentresult = F_grav_vec(pos1,pos2, m1=100, m2=70)
instructorresult = [-4.67201e-07, -0.0, -0.0]
assert vector_error(studentresult, instructorresult ) < 1e-4

# shift positions of both masses by equal amounts
studentresult = F_grav_vec(pos1+4,pos2+4, m1=100, m2=70)
instructorresult = [-4.67201e-07, -0.0, -0.0]
assert vector_error(studentresult, instructorresult ) < 1e-4

# move masses 10x farther apart
studentresult = np.array(F_grav_vec(10*(pos1+4),10*(pos2+4), m1=100, m2=70))
instructorresult = [-4.67201e-09, -0.0, -0.0]
assert vector_error(studentresult, instructorresult ) < 1e-4

del vector_error, studentresult, instructorresult

[-4.67201e-07 -0.00000e+00 -0.00000e+00]
